
CREATE TABLE ICEFOX.ICEFOX_PAGES (
	PID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	CID INTEGER DEFAULT 0 NOT NULL,
	TITLE VARCHAR(200) DEFAULT ' ' NOT NULL,
	SUBTITLE VARCHAR(200) DEFAULT ' ' NOT NULL,
	ACTIVE INTEGER DEFAULT 0 NOT NULL,
	PAGE_HEADER LONG VARCHAR DEFAULT ' ' NOT NULL,
	PAGE_BODY LONG VARCHAR DEFAULT ' ' NOT NULL,
	PAGE_FOOTER LONG VARCHAR DEFAULT ' ' NOT NULL,
	SIGNATURE LONG VARCHAR DEFAULT ' ' NOT NULL,
	DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	COUNTER INTEGER DEFAULT 0 NOT NULL
);

CREATE INDEX ICEFOX_PAGES_PID_IDX ON ICEFOX.ICEFOX_PAGES (PID);

INSERT INTO ICEFOX.ICEFOX_PAGES
(CID, TITLE, SUBTITLE, ACTIVE, PAGE_HEADER, PAGE_BODY, PAGE_FOOTER, SIGNATURE, DATE_CREATED, LAST_UPDATE, COUNTER)
VALUES(0, ' ', ' ', 0, ' ', ' ', ' ', ' ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);





CREATE TABLE ICEFOX.ICEFOX_PAGES_CATEGORIES (
	CID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	CAT_TITLE VARCHAR(200) DEFAULT ' ' NOT NULL,
	CAT_DESC VARCHAR(512) DEFAULT ' ' NOT NULL
);

CREATE INDEX ICEFOX_PAGES_CATEGORIES_CID_IDX ON ICEFOX.ICEFOX_PAGES_CATEGORIES (CID);

INSERT INTO ICEFOX.ICEFOX_PAGES_CATEGORIES
(CAT_TITLE, CAT_DESC)
VALUES(' ', ' ');




