CREATE TABLE ICEFOX.ICEFOX_MESSAGE (
	MESSAGEID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	TITLE VARCHAR(256) DEFAULT ' ' NOT NULL,
	MESSAGE LONG VARCHAR DEFAULT ' ' NOT NULL,
	MESSAGEDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	EXPIREDATE TIMESTAMP DEFAULT TIMESTAMP('2333-01-01 00:00:00') NOT NULL,
	ACTIVE INTEGER DEFAULT 1 NOT NULL,
	MESSAGELANGUAGE VARCHAR(10) DEFAULT 'en' NOT NULL,
	CONSTRAINT MESSAGE_PK PRIMARY KEY (MESSAGEID)
);
