CREATE TABLE ICEFOX.ICEFOX_SECTIONS (
	MID INTEGER AUTOINCREMENT start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	TITLE VARCHAR(100) DEFAULT ' ' NOT NULL,
	CUSTOM_TITLE VARCHAR(100) DEFAULT ' ' NOT NULL,
	ACTIVE INTEGER DEFAULT 0 NOT NULL,
	"VIEW" INTEGER DEFAULT 0 NOT NULL,
	INMENU INTEGER DEFAULT 1 NOT NULL
);

INSERT INTO ICEFOX.ICEFOX_SECTIONS
(TITLE, CUSTOM_TITLE, ACTIVE, "VIEW", INMENU)
VALUES('IceFoxReports', ' ', 0, 0, 1);