CREATE TABLE ICEFOX.ICEFOX_USERS (
RESOURCEID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
RESOURCENAME VARCHAR(100) DEFAULT ' ' NOT NULL,
EMAIL VARCHAR(200) DEFAULT ' ' NOT NULL,
LOGIN VARCHAR(100) NOT NULL,
PSW VARCHAR(512) NOT NULL,
BLOCKED INTEGER DEFAULT 0 NOT NULL
);

CREATE INDEX ICEFOX_USERS_LOGIN_IDX ON ICEFOX.ICEFOX_USERS (LOGIN);



INSERT INTO ICEFOX.ICEFOX_USERS (RESOURCENAME, EMAIL, LOGIN, PSW, BLOCKED)
VALUES(?, ?, ?, ?, 0)


